# Generated by Django 6.0.7 on 2026-07-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verified_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('advisor', 'Advisor')], default='student', max_length=10),
        ),
    ]
