# Generated by Django 6.0.7 on 2026-07-15 00:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailotp_hash_code'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailotp',
            name='accounts_em_user_id_40f783_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='supabase_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Public handle shown on the dashboard. Unique, editable.', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_]{3,20}$', 'Username must be 3–20 characters: lowercase letters, numbers, or underscore.')]),
        ),
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
