# Generated by Django 6.0.7 on 2026-07-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_emailotp_accounts_em_user_id_40f783_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
