# Generated by Django 6.0.7 on 2026-07-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisormessage',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='advisor_audio/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='advisormessage',
            name='audio_duration_seconds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advisormessage',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
