# Generated by Django 6.0.7 on 2026-07-07 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.PositiveSmallIntegerField(help_text='Journey phase 0–6')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('why_it_matters', models.TextField(blank=True, help_text='Shown to the student — every step explains WHY (PRD trust principle)')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('offset_anchor', models.CharField(blank=True, choices=[('application_deadline', 'Application deadline'), ('offer_deadline', 'Offer confirmation deadline'), ('visa_submission', 'Visa submission'), ('intake_start', 'Intake start date'), ('arrival', 'Arrival in Finland')], max_length=30)),
                ('offset_days', models.IntegerField(default=0, help_text='Days relative to the anchor; negative = before')),
                ('is_critical', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['phase', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(default='Pakistan', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('home_city', models.CharField(blank=True, max_length=100)),
                ('study_level', models.CharField(blank=True, choices=[('undergraduate', 'Undergraduate (FSc/A-Levels)'), ('masters', "Masters (Bachelor's degree)")], max_length=20)),
                ('field_of_study', models.CharField(blank=True, max_length=100)),
                ('grades', models.CharField(blank=True, help_text='GPA, percentage, or A-Level grades as entered', max_length=100)),
                ('language_test_status', models.CharField(blank=True, choices=[('not_taken', 'Not taken yet'), ('booked', 'Test booked'), ('taken', 'Score available')], max_length=20)),
                ('language_test_score', models.CharField(blank=True, max_length=20)),
                ('budget_eur_per_year', models.PositiveIntegerField(blank=True, help_text='Annual tuition budget in EUR; null = tuition-free only', null=True)),
                ('intake', models.CharField(blank=True, choices=[('september', 'September'), ('january', 'January')], max_length=20)),
                ('intake_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stage', models.CharField(blank=True, choices=[('exploring', 'Just exploring'), ('ready', 'Ready to apply'), ('applied', 'Already applied')], max_length=20)),
                ('current_phase', models.PositiveSmallIntegerField(default=0)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=100)),
                ('flight_number', models.CharField(max_length=20)),
                ('booking_reference', models.CharField(blank=True, max_length=50)),
                ('depart_airport', models.CharField(help_text='e.g. ISB — Islamabad', max_length=100)),
                ('arrive_airport', models.CharField(help_text='e.g. HEL — Helsinki-Vantaa', max_length=100)),
                ('depart_at', models.DateTimeField()),
                ('arrive_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='students.student')),
            ],
            options={
                'ordering': ['depart_at'],
            },
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('student_housing', 'Student housing (HOAS/TYS/PSOAS…)'), ('private_rental', 'Private rental'), ('temporary', 'Temporary (hostel/Airbnb/friend)')], max_length=20)),
                ('provider', models.CharField(blank=True, help_text='e.g. HOAS, TYS, PSOAS, private landlord', max_length=100)),
                ('status', models.CharField(choices=[('researching', 'Researching'), ('applied', 'Applied'), ('waitlisted', 'Waitlisted'), ('offered', 'Offer received'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='researching', max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('monthly_rent_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('deposit_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('applied_at', models.DateField(blank=True, null=True)),
                ('confirmed_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='students.student')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='students.tasktemplate')),
            ],
            options={
                'ordering': ['phase', 'order', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('passport', 'Passport'), ('photo', 'Passport photo (36×47mm)'), ('transcript', 'Academic transcript'), ('degree_certificate', 'Degree / school certificate'), ('language_certificate', 'IELTS/TOEFL certificate'), ('bank_statement', 'Bank statement'), ('sponsor_letter', 'Financial guarantee / sponsor letter'), ('health_insurance', 'Health insurance'), ('acceptance_letter', 'University acceptance letter'), ('tuition_receipt', 'Tuition payment receipt'), ('accommodation_proof', 'Proof of accommodation'), ('cv', 'CV'), ('motivation_letter', 'Motivation letter'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('ai_reviewed', 'AI reviewed'), ('issues_found', 'Issues found'), ('verified', 'Verified')], default='uploaded', max_length=20)),
                ('ai_review', models.JSONField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, help_text='e.g. passport expiry — Migri needs 15+ months validity', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='applications.application')),
                ('visa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='applications.visa')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['student', 'doc_type'], name='students_do_student_52156d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('channel', models.CharField(choices=[('push', 'Push notification'), ('email', 'Email')], default='push', max_length=10)),
                ('remind_at', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='students.student')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='students.task')),
            ],
            options={
                'ordering': ['remind_at'],
                'indexes': [models.Index(fields=['sent', 'remind_at'], name='students_re_sent_3f81d2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['student', 'phase'], name='students_ta_student_d69942_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['student', 'due_date'], name='students_ta_student_169b64_idx'),
        ),
    ]
