# Generated by Django 6.0.7 on 2026-07-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_assigned_advisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade_scale',
            field=models.CharField(blank=True, choices=[('gpa_4', 'GPA (out of 4)'), ('percentage', 'Percentage'), ('letter', 'Letter grade (O/A-Level)')], help_text='Which scale `grades` is on — drives value validation', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='language_test',
            field=models.CharField(blank=True, choices=[('ielts', 'IELTS'), ('toefl', 'TOEFL iBT'), ('pte', 'PTE Academic'), ('duolingo', 'Duolingo English Test')], help_text='Which English test `language_test_score` is from', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='grades',
            field=models.CharField(blank=True, help_text='Grade value, validated against grade_scale', max_length=100),
        ),
    ]
