# Generated by Django 6.0.7 on 2026-07-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_grade_scale_student_language_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='condition',
            field=models.CharField(blank=True, choices=[('language_test_pending', 'Only while the student has no test score (status ≠ taken)')], default='', max_length=30),
        ),
    ]
