# Generated by Django 6.0.7 on 2026-07-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_tasktemplate_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('photo', 'Passport photo (36×47mm)'), ('transcript', 'Academic transcript'), ('degree_certificate', 'Degree / school certificate'), ('language_certificate', 'IELTS/TOEFL certificate'), ('bank_statement', 'Bank statement'), ('sponsor_letter', 'Financial guarantee / sponsor letter'), ('health_insurance', 'Health insurance'), ('acceptance_letter', 'University acceptance letter'), ('tuition_receipt', 'Tuition payment receipt'), ('accommodation_proof', 'Proof of accommodation'), ('cv', 'CV'), ('motivation_letter', 'Motivation letter'), ('recommendation_letter', 'Letter of recommendation'), ('other', 'Other')], max_length=30),
        ),
    ]
