# Generated by Django 6.0.7 on 2026-07-15 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0003_universityprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('reminder', 'Journey reminder'), ('advisor', 'Advisor message'), ('news', 'News / announcement'), ('update', 'University / policy update'), ('system', 'System'), ('document', 'Document'), ('application', 'Application'), ('visa', 'Visa')], default='news', max_length=20)),
                ('audience', models.CharField(choices=[('all', 'All onboarded students'), ('by_intake_year', 'Students targeting an intake year'), ('by_university', 'Students matched to a university')], default='all', max_length=20)),
                ('intake_year', models.PositiveSmallIntegerField(blank=True, help_text='Required when audience = intake year', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('university', models.ForeignKey(blank=True, help_text='Required when audience = matched university', null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.university')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('reminder', 'Journey reminder'), ('advisor', 'Advisor message'), ('news', 'News / announcement'), ('update', 'University / policy update'), ('system', 'System'), ('document', 'Document'), ('application', 'Application'), ('visa', 'Visa')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'read_at'], name='notificatio_user_id_47e85c_idx')],
            },
        ),
    ]
