# Generated by Django 6.0.7 on 2026-07-07 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('institution_type', models.CharField(choices=[('university', 'University'), ('amk', 'University of Applied Sciences (AMK)')], max_length=20)),
                ('city', models.CharField(help_text='Main campus city', max_length=100)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, help_text='Plain-English description, no bureaucratic language')),
                ('logo_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='universities.university')),
            ],
            options={
                'verbose_name_plural': 'campuses',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('degree_level', models.CharField(choices=[('bachelors', "Bachelor's"), ('masters', "Master's")], max_length=20)),
                ('field_of_study', models.CharField(db_index=True, max_length=100)),
                ('language', models.CharField(default='English', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('duration_years', models.DecimalField(decimal_places=1, default=2, max_digits=3)),
                ('tuition_fee_eur', models.DecimalField(blank=True, decimal_places=2, help_text='Annual tuition for non-EU students; 0 = tuition-free, null = unknown', max_digits=8, null=True)),
                ('scholarship_available', models.BooleanField(default=False)),
                ('scholarship_notes', models.TextField(blank=True)),
                ('intake', models.CharField(choices=[('september', 'September'), ('january', 'January')], max_length=20)),
                ('application_opens', models.DateField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, db_index=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('min_ielts_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('entry_requirements', models.TextField(blank=True, help_text='Plain-English entry requirements')),
                ('acceptance_rate', models.DecimalField(blank=True, decimal_places=1, help_text='Percentage, e.g. 12.5', max_digits=4, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='universities.campus')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='universities.university')),
            ],
            options={
                'ordering': ['university__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('university', 'name', 'degree_level', 'intake'), name='unique_program_per_university')],
            },
        ),
        migrations.AddConstraint(
            model_name='campus',
            constraint=models.UniqueConstraint(fields=('university', 'name'), name='unique_campus_per_university'),
        ),
    ]
