# Generated by Django 6.0.7 on 2026-07-08 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_program_external_id_program_external_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.BooleanField(default=False, help_text='Surface among popular universities')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('overview', models.TextField(blank=True, help_text='Short plain-English editorial overview')),
                ('world_ranking', models.PositiveIntegerField(blank=True, null=True)),
                ('ranking_system', models.CharField(blank=True, choices=[('qs', 'QS World University Rankings'), ('the', 'Times Higher Education'), ('arwu', 'Academic Ranking of World Universities (Shanghai)')], max_length=10)),
                ('ranking_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ranking_source_url', models.URLField(blank=True)),
                ('operational_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateField(blank=True, null=True)),
                ('needs_review', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='universities.university')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'university__name'],
            },
        ),
    ]
