# Generated by Django 6.0.7 on 2026-07-15 18:51

import django.db.models.deletion
import universities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_universityprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=universities.models._doc_type_choices, max_length=30)),
                ('required', models.BooleanField(default=True, help_text='Unticked = optional but recommended')),
                ('notes', models.CharField(blank=True, help_text='Program-specific detail, e.g. "IELTS Academic only, min 6.5"', max_length=200)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='universities.program')),
            ],
            options={
                'ordering': ['program', '-required', 'doc_type'],
                'constraints': [models.UniqueConstraint(fields=('program', 'doc_type'), name='unique_required_doc_per_program')],
            },
        ),
    ]
