# Generated by Django 6.0.7 on 2026-07-07 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('preparing', 'Preparing documents'), ('submitted', 'Submitted on Enter Finland'), ('biometrics_scheduled', 'Embassy/biometrics appointment booked'), ('additional_docs', 'Additional documents requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_started', max_length=30)),
                ('enter_finland_reference', models.CharField(blank=True, max_length=100)),
                ('funds_required_eur', models.DecimalField(blank=True, decimal_places=2, help_text='Migri financial requirement snapshot at application time (changes periodically)', max_digits=8, null=True)),
                ('embassy_location', models.CharField(blank=True, choices=[('islamabad', 'Islamabad (VFS Global)'), ('karachi', 'Karachi')], max_length=20)),
                ('embassy_appointment_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('permit_start', models.DateField(blank=True, null=True)),
                ('permit_end', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('shortlisted', 'Shortlisted'), ('in_progress', 'Preparing application'), ('submitted', 'Submitted'), ('offer_received', 'Offer received'), ('waitlisted', 'Waitlisted'), ('rejected', 'Rejected'), ('place_confirmed', 'Study place confirmed'), ('withdrawn', 'Withdrawn')], default='shortlisted', max_length=20)),
                ('fit', models.CharField(blank=True, choices=[('safety', 'Safety'), ('good_fit', 'Good fit'), ('reach', 'Reach')], help_text='Realistic-chances indicator shown during shortlisting', max_length=10)),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text="Student's own ranking among their applications")),
                ('studyinfo_reference', models.CharField(blank=True, max_length=100)),
                ('motivation_letter', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('offer_confirm_deadline', models.DateField(blank=True, help_text='Missing this cancels the offer', null=True)),
                ('tuition_amount_due_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tuition_payment_reference', models.CharField(blank=True, help_text='Bank transfer reference — most common costly mistake is getting this wrong', max_length=100)),
                ('tuition_paid', models.BooleanField(default=False)),
                ('tuition_paid_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='universities.program')),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
