# Generated by Django 6.0.7 on 2026-07-07 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.student'),
        ),
        migrations.AddField(
            model_name='visa',
            name='application',
            field=models.ForeignKey(blank=True, help_text='The confirmed study place this permit is based on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visas', to='applications.application'),
        ),
        migrations.AddField(
            model_name='visa',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visas', to='students.student'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('student', 'program'), name='unique_application_per_program'),
        ),
    ]
