# Generated by Django 6.0.7 on 2026-07-08 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
        ('students', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit', models.CharField(choices=[('safety', 'Safety'), ('good_fit', 'Good fit'), ('reach', 'Reach')], max_length=10)),
                ('score', models.DecimalField(decimal_places=2, help_text='0–100 composite fit score', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='universities.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['-score'],
                'constraints': [models.UniqueConstraint(fields=('student', 'program'), name='unique_match_per_program')],
            },
        ),
    ]
