# Generated by Django 6.0.7 on 2026-07-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. migri_monthly_funds_eur', max_length=60, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, help_text='e.g. EUR/month, hours/week', max_length=40)),
                ('source_url', models.URLField(blank=True)),
                ('needs_verification', models.BooleanField(default=False, help_text="Flagged when the seeded value hasn't been confirmed against the source")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
