# Generated by Django 6.0.7 on 2026-07-08 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('scraper_key', models.CharField(help_text='Key registered in scraping.scrapers.SCRAPER_REGISTRY', max_length=100)),
                ('url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_scraped', models.PositiveIntegerField(default=0)),
                ('changes_detected', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='scraping.scrapesource')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DataChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('field_name', models.CharField(max_length=100)),
                ('old_display', models.TextField(blank=True)),
                ('new_display', models.TextField(blank=True)),
                ('new_value', models.JSONField(help_text='Raw scraped value, coerced to the field type on apply')),
                ('risk', models.CharField(choices=[('low', 'Low'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='pending_review', max_length=15)),
                ('applied_automatically', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='scraping.scraperun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'risk'], name='scraping_da_status_845237_idx')],
            },
        ),
    ]
