# Generated by Django 6.0.7 on 2026-07-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperun',
            name='records_created',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
